### ISSUE TITLE
Recipe Stuff

### ISSUE THREAD

**Issue by Moshambi** [hardlydifficult/factory#22]
I will add more here when I get the amounts for you.

So far here is a dough recipe.

## Pizza Dough

Pretty basic recipe.

**Dry Ingredients**
- 3.5 Cups Flour
- 1 Tablespoon Sugar
- 1 Teaspoon Salt
- .25 Ounces Yeast (1 packet)

**Wet Ingredients**
- 1 Cup Warm Water
- 1 Tablespoon Olive Oil

**Instructions**
First, mix the warm water and yeast and set aside.

Put all the dry ingredients into a bowl and mix. Make a hollowed out circle in the center and pour the water/yeast mixture into the hole. Add the oil and then mix.

Knead the dough and form a dough ball. Depending on the type of yeast you use the rise time will be different. I personally use the rapid rise yeast so that a dough ball can be made and then rise enough in ~15 minutes before being ready to use.

Takes 15 minutes to cook in this oven: https://www.katom.com/067-1023221.html

**Comment by HardlyDifficult** [comment]
Old... closing.. thanks
