### ISSUE TITLE
Sound selection #1

### ISSUE THREAD

**Issue by btastic** [hardlydifficult/factory#4]
I made a small selection of stuff you could use for your game. It is mostly factory noises. Money noises. And other stuff that might come in handy.

The files were downloaded from this thread on reddit: https://www.reddit.com/r/gamedev/comments/5whve2/20gb_of_high_quality_sound_effects_the_sonniss/

In case the thread get's deleted I will keep the original text here:

> Hey guys, hope you are all well.
> This is Timothy McHugh here from Sonniss.
> I am not sure if any of you remember me, but last year I dropped 16GB of free sound effects for you all in celebration of GDC, and the year before that I gave away 10gb of sound effects. You can view the original threads here! and here!
> Well my fellow redditors, it’s that time of year again and I need your help. I have 20GB+ here for you all this year. Everything is royalty-free, commercially-usable and no attribution is required. It's the biggest library we have released so far and you can use them in your games however you please!
> Visit the website: http://www.sonniss.com/gameaudiogdc2017/
> View the license: http://www.sonniss.com/gdc-bundle-license
> OFFICIAL TORRENT: http://sonniss.com/GameAudioGDCPart3.torrent
> Once you have downloaded the files, please help by sharing, seeding or uploading them to mirrors. Thank you in advance.
> If you have any questions or concerns please leave them in the comments section below. I will be over in the reddit gamedev irc channel throughout the day.
> Enjoy.
> PLEASE NOTE: The Torrent is pretty slow right now, I could do with some people downloading the files via the direct links and populating the folder structure if possible... Thanks in advance. Let's get this thing going!

I decided to reupload the selection anyway because I don't think we hurt anyone with it.

I also kept the original README.txt and the Licensing.pdf that came with the torrent for your safety.

Download link: https://mega.nz/#!m182hKjK!zzOgvLHC9PYvypR0lgOqkMDn7t4L2M3TpkEjmk4WzWE

**Comment by HardlyDifficult** [comment]
These are sound effects!  I thought it was music.

**Comment by HardlyDifficult** [comment]
Old... closing.. thanks
